version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name work-esaki --s3-location s3://work-ens3/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src